# Generated by Django 5.0.7 on 2024-12-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('nombreTaller', models.CharField(max_length=100)),
                ('direccion', models.IntegerField()),
                ('horario1', models.CharField(max_length=15)),
                ('horario2', models.CharField(max_length=15)),
                ('profesor', models.CharField(max_length=100)),
            ],
        ),
    ]
