# Generated by Django 5.0.7 on 2024-12-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='horario2',
        ),
        migrations.AlterField(
            model_name='taller',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taller',
            name='horario1',
            field=models.CharField(max_length=20),
        ),
    ]
