# Generated by Django 5.0.7 on 2024-12-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='horario1',
            field=models.CharField(max_length=50),
        ),
    ]
